package com.gapinc.booking.domain;
// Generated 2016-12-15 14:34:43 by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingT generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "xiaohei")
public class Booking implements java.io.Serializable {

	private String gisBookId;
	private String gisBookStatus;
	private String sourceAttribute;
	private String receiptId;
	private String receiptIntent;
	private String receiptStatus;
	private String receiptType;
	private Date indcDate;
	private String indcFiscalYear;
	private Integer indcFiscalMonth;
	private String indcFiscalWeek;
	private Date inStoreDate;
	private Integer publishedUnit;
	private Integer confirmedUnit;
	private String optionId;
	private Long factoryProfileId;
	private String factoryName;
	private String rscType;
	private Integer flaggedReasonCode;
	private String visibleToVendorInd;
	private String changeInd;
	private String delInd;
	private Date receiptPublishedDate;
	private String receiptPublishedBy;
	private Date receiptConfirmedDate;
	private String receiptConfirmedBy;
	private String currentReceiptInd;
	private Long associatedBookId;
	private Integer currentVersionNum;

	public Booking() {
	}

	public Booking(String gisBookId) {
		this.gisBookId = gisBookId;
	}

	public Booking(String gisBookId, String gisBookStatus, String sourceAttribute, String receiptId,
			String receiptIntent, String receiptStatus, String receiptType, Date indcDate, String indcFiscalYear,
			Integer indcFiscalMonth, String indcFiscalWeek, Date inStoreDate, Integer publishedUnit,
			Integer confirmedUnit, String optionId, Long factoryProfileId, String factoryName, String rscType,
			Integer flaggedReasonCode, String visibleToVendorInd, String changeInd, String delInd,
			Date receiptPublishedDate, String receiptPublishedBy, Date receiptConfirmedDate, String receiptConfirmedBy,
			String currentReceiptInd, Long associatedBookId, Integer currentVersionNum) {
		this.gisBookId = gisBookId;
		this.gisBookStatus = gisBookStatus;
		this.sourceAttribute = sourceAttribute;
		this.receiptId = receiptId;
		this.receiptIntent = receiptIntent;
		this.receiptStatus = receiptStatus;
		this.receiptType = receiptType;
		this.indcDate = indcDate;
		this.indcFiscalYear = indcFiscalYear;
		this.indcFiscalMonth = indcFiscalMonth;
		this.indcFiscalWeek = indcFiscalWeek;
		this.inStoreDate = inStoreDate;
		this.publishedUnit = publishedUnit;
		this.confirmedUnit = confirmedUnit;
		this.optionId = optionId;
		this.factoryProfileId = factoryProfileId;
		this.factoryName = factoryName;
		this.rscType = rscType;
		this.flaggedReasonCode = flaggedReasonCode;
		this.visibleToVendorInd = visibleToVendorInd;
		this.changeInd = changeInd;
		this.delInd = delInd;
		this.receiptPublishedDate = receiptPublishedDate;
		this.receiptPublishedBy = receiptPublishedBy;
		this.receiptConfirmedDate = receiptConfirmedDate;
		this.receiptConfirmedBy = receiptConfirmedBy;
		this.currentReceiptInd = currentReceiptInd;
		this.associatedBookId = associatedBookId;
		this.currentVersionNum = currentVersionNum;
	}

	@Id
	@Column(name = "GIS_BOOK_ID", unique = true, nullable = false, length = 50)
	public String getGisBookId() {
		return this.gisBookId;
	}

	public void setGisBookId(String gisBookId) {
		this.gisBookId = gisBookId;
	}

	@Column(name = "GIS_BOOK_STATUS", length = 50)
	public String getGisBookStatus() {
		return this.gisBookStatus;
	}

	public void setGisBookStatus(String gisBookStatus) {
		this.gisBookStatus = gisBookStatus;
	}

	@Column(name = "SOURCE_ATTRIBUTE", length = 50)
	public String getSourceAttribute() {
		return this.sourceAttribute;
	}

	public void setSourceAttribute(String sourceAttribute) {
		this.sourceAttribute = sourceAttribute;
	}

	@Column(name = "RECEIPT_ID", length = 50)
	public String getReceiptId() {
		return this.receiptId;
	}

	public void setReceiptId(String receiptId) {
		this.receiptId = receiptId;
	}

	@Column(name = "RECEIPT_INTENT", length = 50)
	public String getReceiptIntent() {
		return this.receiptIntent;
	}

	public void setReceiptIntent(String receiptIntent) {
		this.receiptIntent = receiptIntent;
	}

	@Column(name = "RECEIPT_STATUS", length = 50)
	public String getReceiptStatus() {
		return this.receiptStatus;
	}

	public void setReceiptStatus(String receiptStatus) {
		this.receiptStatus = receiptStatus;
	}

	@Column(name = "RECEIPT_TYPE", length = 50)
	public String getReceiptType() {
		return this.receiptType;
	}

	public void setReceiptType(String receiptType) {
		this.receiptType = receiptType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INDC_DATE", length = 23)
	public Date getIndcDate() {
		return this.indcDate;
	}

	public void setIndcDate(Date indcDate) {
		this.indcDate = indcDate;
	}

	@Column(name = "INDC_FISCAL_YEAR", length = 9)
	public String getIndcFiscalYear() {
		return this.indcFiscalYear;
	}

	public void setIndcFiscalYear(String indcFiscalYear) {
		this.indcFiscalYear = indcFiscalYear;
	}

	@Column(name = "INDC_FISCAL_MONTH")
	public Integer getIndcFiscalMonth() {
		return this.indcFiscalMonth;
	}

	public void setIndcFiscalMonth(Integer indcFiscalMonth) {
		this.indcFiscalMonth = indcFiscalMonth;
	}

	@Column(name = "INDC_FISCAL_WEEK", length = 50)
	public String getIndcFiscalWeek() {
		return this.indcFiscalWeek;
	}

	public void setIndcFiscalWeek(String indcFiscalWeek) {
		this.indcFiscalWeek = indcFiscalWeek;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IN_STORE_DATE", length = 10)
	public Date getInStoreDate() {
		return this.inStoreDate;
	}

	public void setInStoreDate(Date inStoreDate) {
		this.inStoreDate = inStoreDate;
	}

	@Column(name = "PUBLISHED_UNIT")
	public Integer getPublishedUnit() {
		return this.publishedUnit;
	}

	public void setPublishedUnit(Integer publishedUnit) {
		this.publishedUnit = publishedUnit;
	}

	@Column(name = "CONFIRMED_UNIT")
	public Integer getConfirmedUnit() {
		return this.confirmedUnit;
	}

	public void setConfirmedUnit(Integer confirmedUnit) {
		this.confirmedUnit = confirmedUnit;
	}

	@Column(name = "OPTION_ID", length = 50)
	public String getOptionId() {
		return this.optionId;
	}

	public void setOptionId(String optionId) {
		this.optionId = optionId;
	}

	@Column(name = "FACTORY_PROFILE_ID")
	public Long getFactoryProfileId() {
		return this.factoryProfileId;
	}

	public void setFactoryProfileId(Long factoryProfileId) {
		this.factoryProfileId = factoryProfileId;
	}

	@Column(name = "FACTORY_NAME", length = 100)
	public String getFactoryName() {
		return this.factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	@Column(name = "RSC_TYPE", length = 50)
	public String getRscType() {
		return this.rscType;
	}

	public void setRscType(String rscType) {
		this.rscType = rscType;
	}

	@Column(name = "FLAGGED_REASON_CODE")
	public Integer getFlaggedReasonCode() {
		return this.flaggedReasonCode;
	}

	public void setFlaggedReasonCode(Integer flaggedReasonCode) {
		this.flaggedReasonCode = flaggedReasonCode;
	}

	@Column(name = "VISIBLE_TO_VENDOR_IND", length = 1)
	public String getVisibleToVendorInd() {
		return this.visibleToVendorInd;
	}

	public void setVisibleToVendorInd(String visibleToVendorInd) {
		this.visibleToVendorInd = visibleToVendorInd;
	}

	@Column(name = "CHANGE_IND", length = 1)
	public String getChangeInd() {
		return this.changeInd;
	}

	public void setChangeInd(String changeInd) {
		this.changeInd = changeInd;
	}

	@Column(name = "DEL_IND", length = 1)
	public String getDelInd() {
		return this.delInd;
	}

	public void setDelInd(String delInd) {
		this.delInd = delInd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIPT_PUBLISHED_DATE", length = 23)
	public Date getReceiptPublishedDate() {
		return this.receiptPublishedDate;
	}

	public void setReceiptPublishedDate(Date receiptPublishedDate) {
		this.receiptPublishedDate = receiptPublishedDate;
	}

	@Column(name = "RECEIPT_PUBLISHED_BY", length = 250)
	public String getReceiptPublishedBy() {
		return this.receiptPublishedBy;
	}

	public void setReceiptPublishedBy(String receiptPublishedBy) {
		this.receiptPublishedBy = receiptPublishedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIPT_CONFIRMED_DATE", length = 23)
	public Date getReceiptConfirmedDate() {
		return this.receiptConfirmedDate;
	}

	public void setReceiptConfirmedDate(Date receiptConfirmedDate) {
		this.receiptConfirmedDate = receiptConfirmedDate;
	}

	@Column(name = "RECEIPT_CONFIRMED_BY", length = 50)
	public String getReceiptConfirmedBy() {
		return this.receiptConfirmedBy;
	}

	public void setReceiptConfirmedBy(String receiptConfirmedBy) {
		this.receiptConfirmedBy = receiptConfirmedBy;
	}

	@Column(name = "CURRENT_RECEIPT_IND", length = 1)
	public String getCurrentReceiptInd() {
		return this.currentReceiptInd;
	}

	public void setCurrentReceiptInd(String currentReceiptInd) {
		this.currentReceiptInd = currentReceiptInd;
	}

	@Column(name = "ASSOCIATED_BOOK_ID")
	public Long getAssociatedBookId() {
		return this.associatedBookId;
	}

	public void setAssociatedBookId(Long associatedBookId) {
		this.associatedBookId = associatedBookId;
	}

	@Column(name = "CURRENT_VERSION_NUM")
	public Integer getCurrentVersionNum() {
		return this.currentVersionNum;
	}

	public void setCurrentVersionNum(Integer currentVersionNum) {
		this.currentVersionNum = currentVersionNum;
	}

}
