package com.gapinc.booking.domain;
// Generated 2017-6-14 0:45:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XhCase generated by hbm2java
 */
@Entity
@Table(name = "xh_case", catalog = "xiaohei")
public class XhCase implements java.io.Serializable {

	private String id;
	private String title;
	private String company;
	private Date caseDate;
	private String address;
	private String content;
	private Date createTime;

	public XhCase() {
	}

	public XhCase(String id) {
		this.id = id;
	}

	public XhCase(String id, String title, String company, Date caseDate, String address, String content,
			Date createTime) {
		this.id = id;
		this.title = title;
		this.company = company;
		this.caseDate = caseDate;
		this.address = address;
		this.content = content;
		this.createTime = createTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "company", length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "case_date", length = 10)
	public Date getCaseDate() {
		return this.caseDate;
	}

	public void setCaseDate(Date caseDate) {
		this.caseDate = caseDate;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
