package com.gapinc.booking.domain;
// Generated 2017-6-14 0:45:41 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * XhContact generated by hbm2java
 */
@Entity
@Table(name = "xh_contact", catalog = "xiaohei")
public class XhContact implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1213539867795658960L;
	private String id;
	private String info;
	private String tel;
	private String phone;
	private String email;
	private String address;
	private String image;
	private String contacts;

	public XhContact() {
	}

	public XhContact(String id) {
		this.id = id;
	}

	public XhContact(String id, String info, String tel, String phone, String email, String address, String image,
			String contacts) {
		this.id = id;
		this.info = info;
		this.tel = tel;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.image = image;
		this.contacts = contacts;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "contacts", length = 10)
	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

}
