package com.gapinc.booking.domain;
// Generated 2017-6-14 0:45:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XhProduct generated by hbm2java
 */
@Entity
@Table(name = "xh_product", catalog = "xiaohei")
public class XhProduct implements java.io.Serializable {

	private String id;
	private String name;
	private String img;
	private String content;
	private Boolean isSend;
	private Integer sort;
	private Boolean isDelete;
	private Date createTime;

	public XhProduct() {
	}

	public XhProduct(String id) {
		this.id = id;
	}

	public XhProduct(String id, String name, String img, String content, Boolean isSend, Integer sort, Boolean isDelete,
			Date createTime) {
		this.id = id;
		this.name = name;
		this.img = img;
		this.content = content;
		this.isSend = isSend;
		this.sort = sort;
		this.isDelete = isDelete;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "img", length = 300)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "is_send")
	public Boolean getIsSend() {
		return this.isSend;
	}

	public void setIsSend(Boolean isSend) {
		this.isSend = isSend;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "is_delete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
